export const DIMENSIONS = [
  {
    id: 'completeness',
    name: 'Completeness',
    weight: 0.15,
    criteria: [
      'Executive summary / project overview present',
      'Business objectives clearly stated',
      'Scope definition (in-scope and out-of-scope)',
      'Functional requirements section',
      'Non-functional requirements section',
      'Stakeholder list with roles',
      'Assumptions and constraints documented',
      'Timeline / milestones included',
      'Budget / cost considerations mentioned',
      'Glossary / definitions section',
    ],
  },
  {
    id: 'clarity',
    name: 'Clarity & Readability',
    weight: 0.10,
    criteria: [
      'Unambiguous language throughout',
      'Acronyms defined on first use',
      'Consistent terminology',
      'Appropriate level of detail',
      'Well-structured sentences',
      'No jargon without explanation',
    ],
  },
  {
    id: 'requirements_quality',
    name: 'Requirements Quality',
    weight: 0.15,
    criteria: [
      'Requirements are Specific',
      'Requirements are Measurable',
      'Requirements are Achievable',
      'Requirements are Relevant',
      'Requirements are Time-bound',
      'Each requirement is testable/verifiable',
      'No vague terms (should be fast, user-friendly, etc.)',
      'Proper use of shall/should/may',
      'Requirements are atomic (one requirement per statement)',
    ],
  },
  {
    id: 'consistency',
    name: 'Consistency',
    weight: 0.10,
    criteria: [
      'No contradictions between sections',
      'Consistent naming conventions',
      'Scope aligns with requirements',
      'Objectives align with requirements',
      'Consistent formatting throughout',
    ],
  },
  {
    id: 'traceability',
    name: 'Traceability',
    weight: 0.08,
    criteria: [
      'Requirements have unique identifiers (IDs)',
      'Cross-references between related requirements',
      'Requirements trace back to business objectives',
      'Dependencies between requirements documented',
      'Traceability matrix present or referenced',
    ],
  },
  {
    id: 'feasibility',
    name: 'Feasibility & Realism',
    weight: 0.10,
    criteria: [
      'Technical feasibility considered',
      'Realistic timelines proposed',
      'Resource requirements identified',
      'Technology constraints acknowledged',
      'Integration considerations documented',
    ],
  },
  {
    id: 'stakeholder_coverage',
    name: 'Stakeholder Coverage',
    weight: 0.08,
    criteria: [
      'All stakeholder groups identified',
      'Roles and responsibilities defined (RACI)',
      'Approval process documented',
      'Communication plan referenced',
      'Sign-off requirements clear',
    ],
  },
  {
    id: 'risk_constraints',
    name: 'Risk & Constraints',
    weight: 0.08,
    criteria: [
      'Risks identified and documented',
      'Risk mitigation strategies provided',
      'Constraints explicitly stated',
      'Assumptions documented with rationale',
      'Impact analysis for key risks',
    ],
  },
  {
    id: 'acceptance_criteria',
    name: 'Acceptance Criteria',
    weight: 0.08,
    criteria: [
      'Measurable acceptance criteria for each requirement',
      'Success metrics defined',
      'Testing approach referenced',
      'User acceptance criteria specified',
      'Performance benchmarks stated',
    ],
  },
  {
    id: 'standards_compliance',
    name: 'Standards Compliance',
    weight: 0.08,
    criteria: [
      'Follows organizational document template',
      'Industry standards referenced (BABOK, IEEE)',
      'Proper document versioning',
      'Change history maintained',
      'Regulatory compliance addressed if applicable',
    ],
  },
];
