import jsPDF from 'jspdf';
import 'jspdf-autotable';

export function generatePdf(result) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Cover page
  doc.setFillColor(27, 58, 92); // Navy
  doc.rect(0, 0, pageWidth, 297, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.text('Giza Systems', 20, 30);

  doc.setFontSize(28);
  doc.text('BRD Quality', 20, 80);
  doc.text('Assurance Report', 20, 95);

  doc.setFontSize(14);
  doc.text(result.metadata?.projectName || 'BRD Document', 20, 120);

  doc.setFontSize(11);
  doc.text(`Version: ${result.metadata?.version || 'N/A'}`, 20, 140);
  doc.text(`Author: ${result.metadata?.author || 'N/A'}`, 20, 150);
  doc.text(`Domain: ${result.metadata?.domain || 'N/A'}`, 20, 160);
  doc.text(`Date: ${new Date(result.analyzedAt).toLocaleDateString()}`, 20, 170);

  // Score circle
  doc.setFillColor(232, 121, 47); // Accent
  doc.circle(pageWidth - 50, 90, 30, 'F');
  doc.setFontSize(24);
  doc.setTextColor(255, 255, 255);
  doc.text(String(result.overallScore), pageWidth - 50, 88, { align: 'center' });
  doc.setFontSize(14);
  doc.text(result.healthGrade, pageWidth - 50, 100, { align: 'center' });

  // Page 2: Executive Summary
  doc.addPage();
  doc.setTextColor(27, 58, 92);
  doc.setFontSize(20);
  doc.text('Executive Summary', 20, 25);

  doc.setFontSize(11);
  doc.setTextColor(80, 80, 80);
  doc.text(`Overall Score: ${result.overallScore}/100 (${result.healthGrade})`, 20, 40);
  doc.text(`Total Findings: ${result.findings?.length || 0}`, 20, 48);
  doc.text(`Critical Issues: ${result.findings?.filter(f => f.severity === 'critical').length || 0}`, 20, 56);
  doc.text(`Strengths Identified: ${result.strengths?.length || 0}`, 20, 64);

  // Dimension Scores Table
  doc.setFontSize(16);
  doc.setTextColor(27, 58, 92);
  doc.text('Dimension Scores', 20, 85);

  doc.autoTable({
    startY: 92,
    head: [['Dimension', 'Score', 'Grade', 'Findings']],
    body: result.dimensions?.map(d => [
      d.name,
      `${d.score}/100`,
      d.grade,
      d.findings?.length || 0,
    ]) || [],
    headStyles: { fillColor: [27, 58, 92], textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [245, 247, 250] },
    styles: { fontSize: 9 },
  });

  // Page 3: Findings
  doc.addPage();
  doc.setFontSize(20);
  doc.setTextColor(27, 58, 92);
  doc.text('Findings', 20, 25);

  doc.autoTable({
    startY: 32,
    head: [['Severity', 'Dimension', 'Title', 'Recommendation']],
    body: result.findings?.map(f => [
      f.severity?.toUpperCase(),
      result.dimensions?.find(d => d.id === f.dimensionId)?.name || f.dimensionId,
      f.title,
      f.recommendation,
    ]) || [],
    headStyles: { fillColor: [27, 58, 92], textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [245, 247, 250] },
    styles: { fontSize: 8, cellWidth: 'wrap' },
    columnStyles: {
      0: { cellWidth: 22 },
      1: { cellWidth: 30 },
      2: { cellWidth: 55 },
      3: { cellWidth: 'auto' },
    },
  });

  // Page 4: Priority Actions
  doc.addPage();
  doc.setFontSize(20);
  doc.setTextColor(27, 58, 92);
  doc.text('Priority Actions', 20, 25);

  doc.autoTable({
    startY: 32,
    head: [['#', 'Action', 'Impact', 'Effort', 'Description']],
    body: result.priorityActions?.map(a => [
      a.rank,
      a.title,
      a.impact,
      a.effort,
      a.description,
    ]) || [],
    headStyles: { fillColor: [27, 58, 92], textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [245, 247, 250] },
    styles: { fontSize: 8 },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { cellWidth: 35 },
      4: { cellWidth: 'auto' },
    },
  });

  // Footer on each page
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 2; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      'Generated by BRD Quality Assurance Tool | Giza Systems',
      pageWidth / 2, 290,
      { align: 'center' }
    );
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - 20, 290, { align: 'right' });
  }

  doc.save(`BRD-QA-Report-${result.metadata?.projectName || 'report'}.pdf`);
}
